name: nuxt-app
private: true
type: module

engines:
  node: ">= 22"
  pnpm: ">= 9"

scripts:
  build: nuxt build
  dev: nuxt dev
  generate: nuxt generate
  preview: nuxt preview
  postinstall: nuxt prepare
  typecheck: nuxt typecheck

  prepare: husky

  clean: pnpx jiti scripts/clean.ts

  test:unit:watch: vitest
  test:unit: vitest --run
  test:e2e:ui: playwright test --ui
  test:e2e: playwright test

  lint: pnpm lint:es && pnpm lint:style
  lint:es: eslint --max-warnings 0
  lint:style: stylelint  "**/*.{css,less,scss,sass,styl,stylus,pcss,postcss,sss,vue}"
  lint:fix: pnpm lint:es:fix && pnpm lint:style:fix
  lint:es:fix: pnpm lint:es --fix
  lint:style:fix: pnpm lint:style --fix

  # Task to create package.json for tools that need it
  create-package-json: pnpx jiti scripts/compile-package-json.ts

  # Workaround for:
  # - ESLint requiring a package.json
  # - Vitest to load ESM modules, as it needs to see "type": "module" in package.json
  # - Nuxt needing package.json to typecheck properly
  pnpm:devPreinstall: pnpm create-package-json

dependencies:
  # For linting
  "@nuxt/eslint": ^1.0.0
  eslint-plugin-vue-pug: ^0.6.2 # ESLint rules for Pug
  "@eslint/eslintrc": ^3.2.0 # To convert eslint-plugin-vue-pug to new ESLint flat config format
  "@types/eslint__eslintrc": ^2.1.2
  yaml: ^2.7.0

  "@nuxt/fonts": ^0.10.3

  nuxt: ^3.15.4
  vue: latest

devDependencies:
  # Enable use of TypeScript config files in various tools
  jiti: ^2.4.2

  # To use Sass
  sass-embedded: ^1.83.4

  # For testing
  "@nuxt/test-utils": ^3.15.4
  "@playwright/test": ^1.50.1
  "@vue/test-utils": ^2.4.6
  jsdom: ^26.0.0
  std-env: ^3.8.0
  vitest: ^3.0.4
  "monocart-reporter": ^2.9.13

  # For code quality checks on pre-commit
  husky: ^9.1.7
  lint-staged: ^15.4.3

  # To use Pug in Vue templates
  "@vue/language-plugin-pug": ^2.2.0 # Enables autocompletion for Vue components in Pug templates
  pug: ^3.0.3

  # To enable typechecking
  typescript: ^5.7.3
  vue-tsc: ^2.2.0

  # For linting stylesheets
  "@nuxtjs/stylelint-module": ^5.2.0
  stylelint: ^16.14.1
  stylelint-config-standard-scss: ^14.0.0
  stylelint-config-standard-vue: ^1.0.0
  # Use SugarSS as a pseudo-sass parser due to postcss-sass not working with media queries
  postcss-sass: npm:sugarss@latest
  postcss-html: ^1.8.0

packageManager: pnpm@9.15.4+sha512.b2dc20e2fc72b3e18848459b37359a32064663e5627a51e4c74b2c29dd8e8e0491483c3abb40789cfd578bf362fb6ba8261b05f0387d76792ed6e23ea3b1b6a0
