name: nuxt-app
private: true
type: module

engines:
  node: ">= 22"
  pnpm: ">= 10.6.3"

scripts:
  build: nuxt build
  dev: nuxt dev
  generate: nuxt generate
  preview: nuxt preview
  postinstall: nuxt prepare
  typecheck: nuxt typecheck

  prepare: husky

  clean: pnpx jiti scripts/clean.ts

  test:unit:watch: vitest
  test:unit: vitest --run
  test:e2e:ui: playwright test --ui
  test:e2e: playwright test

  lint: pnpm lint:es && pnpm lint:style
  lint:es: eslint --max-warnings 0
  lint:style: stylelint  "**/*.{css,less,scss,sass,styl,stylus,pcss,postcss,sss,vue}"
  lint:fix: pnpm lint:es:fix && pnpm lint:style:fix
  lint:es:fix: pnpm lint:es --fix
  lint:style:fix: pnpm lint:style --fix

  # Task to create package.json for tools that need it
  compile:packageJson: pnpx jiti scripts/compilePackageJson.ts

  # Workaround for:
  # - ESLint requiring a package.json
  # - Vitest to load ESM modules, as it needs to see "type": "module" in package.json
  # - Nuxt needing package.json to typecheck properly
  pnpm:devPreinstall: pnpm compile:packageJson

dependencies:
  # For linting
  ## This is in dependencies due to how Nuxt builds
  "@nuxt/eslint": ^1.2.0
  eslint: ^9.23.0
  eslint-plugin-vue-pug: ^0.6.2 # ESLint rules for Pug
  "@eslint/eslintrc": ^3.3.1 # To convert eslint-plugin-vue-pug to new ESLint flat config format
  yaml: ^2.7.0

  "@nuxt/fonts": ^0.11.0

  nuxt: ^3.16.1
  vue: latest

devDependencies:
  # Enable use of TypeScript config files in various tools
  jiti: ^2.4.2

  # To use Sass
  sass-embedded: ^1.86.0

  # For testing
  "@nuxt/test-utils": ^3.17.2
  "@playwright/test": ^1.51.1
  "@vue/test-utils": ^2.4.6
  jsdom: ^26.0.0
  std-env: ^3.8.1
  vitest: ^3.0.9
  "monocart-reporter": ^2.9.16

  # For code quality checks on pre-commit
  husky: ^9.1.7
  lint-staged: ^15.5.0

  # To use Pug in Vue templates
  "@vue/language-plugin-pug": ^2.2.8 # Enables autocompletion for Vue components in Pug templates
  pug: ^3.0.3

  # To enable typechecking
  typescript: ^5.8.2
  vue-tsc: ^2.2.8

  # For linting stylesheets
  "@nuxtjs/stylelint-module": ^5.2.1
  stylelint: ^16.16.0
  stylelint-config-standard-scss: ^14.0.0
  stylelint-config-standard-vue: ^1.0.0
  # Use SugarSS as a pseudo-sass parser due to postcss-sass not working with media queries
  postcss-sass: npm:sugarss@latest
  postcss-html: ^1.8.0

packageManager: pnpm@10.6.5+sha512.cdf928fca20832cd59ec53826492b7dc25dc524d4370b6b4adbf65803d32efaa6c1c88147c0ae4e8d579a6c9eec715757b50d4fa35eea179d868eada4ed043af"

pnpm:
  onlyBuiltDependencies:
    - "@parcel/watcher"
    - esbuild
