name: nuxt-app
private: true
type: module

devEngines:
  packageManager:
    name: pnpm
    version: 10.11.1+sha512.e519b9f7639869dc8d5c3c5dfef73b3f091094b0a006d7317353c72b124e80e1afd429732e28705ad6bfa1ee879c1fce46c128ccebd3192101f43dd67c667912
    onFail: download

engines:
  node: ">= 24"

scripts:
  build: nuxt build
  dev: nuxt dev
  generate: nuxt generate
  preview: nuxt preview
  postinstall: nuxt prepare
  typecheck: nuxt typecheck

  prepare: husky

  clean: pnpx jiti scripts/clean.ts

  test:unit:watch: vitest
  test:unit: vitest --run
  test:e2e:ui: playwright test --ui
  test:e2e: playwright test

  lint: pnpm lint:es && pnpm lint:style
  lint:es: eslint --max-warnings 0
  lint:style: stylelint  "**/*.{css,less,scss,sass,styl,stylus,pcss,postcss,sss,vue}"
  lint:fix: pnpm lint:es:fix && pnpm lint:style:fix
  lint:es:fix: pnpm lint:es --fix
  lint:style:fix: pnpm lint:style --fix

  # Task to create package.json for tools that need it
  compile:packageJson: pnpx jiti scripts/compilePackageJson.ts

  # Workaround for:
  # - ESLint requiring a package.json
  # - Vitest to load ESM modules, as it needs to see "type": "module" in package.json
  # - Nuxt needing package.json to typecheck properly
  pnpm:devPreinstall: pnpm compile:packageJson

dependencies:
  # For linting
  ## This is in dependencies due to how Nuxt builds
  "@nuxt/eslint": ^1.4.1
  eslint: ^9.28.0
  eslint-plugin-n: ^17.19.0
  eslint-plugin-vue-pug: ^0.6.2 # ESLint rules for Pug
  "@eslint/eslintrc": ^3.3.1 # To convert eslint-plugin-vue-pug to new ESLint flat config format
  yaml: ^2.8.0

  "@nuxt/fonts": ^0.11.4

  nuxt: ^3.17.5
  vue: latest

devDependencies:
  # Enable use of TypeScript config files in various tools
  jiti: ^2.4.2

  # To use Sass
  sass-embedded: ^1.89.1

  # For testing
  "@nuxt/test-utils": ^3.19.1
  "@playwright/test": ^1.52.0
  "@vue/test-utils": ^2.4.6
  jsdom: ^26.1.0
  std-env: ^3.9.0
  vitest: ^3.2.2
  "monocart-reporter": ^2.9.20

  # For code quality checks on pre-commit
  husky: ^9.1.7
  lint-staged: ^16.1.0

  # To use Pug in Vue templates
  "@vue/language-plugin-pug": ^2.2.10 # Enables autocompletion for Vue components in Pug templates
  pug: ^3.0.3

  # To enable typechecking
  typescript: ^5.8.3
  vue-tsc: ^2.2.10

  # For linting stylesheets
  "@nuxtjs/stylelint-module": ^5.2.1
  stylelint: ^16.20.0
  stylelint-config-standard-scss: ^15.0.1
  stylelint-config-standard-vue: ^1.0.0
  # Use SugarSS as a pseudo-sass parser due to postcss-sass not working with media queries
  postcss-sass: npm:sugarss@latest
  postcss-html: ^1.8.0
