name: nuxt-app
private: true
type: module

devEngines:
  packageManager:
    name: pnpm
    version: 10.15.0+sha512.486ebc259d3e999a4e8691ce03b5cac4a71cbeca39372a9b762cb500cfdf0873e2cb16abe3d951b1ee2cf012503f027b98b6584e4df22524e0c7450d9ec7aa7b
    onFail: download

engines:
  node: '>= 24'

scripts:
  build: nuxt build
  dev: nuxt dev
  generate: nuxt generate
  preview: nuxt preview
  postinstall: nuxt prepare
  typecheck: nuxt typecheck

  prepare: husky

  clean: pnpx jiti scripts/clean.ts

  test:unit:watch: vitest
  test:unit: vitest --run
  test:e2e:ui: playwright test --ui
  test:e2e: playwright test

  lint: pnpm lint:es && pnpm lint:style
  lint:es: eslint --max-warnings 0
  lint:style: stylelint "**/*.{css,less,scss,sass,styl,stylus,pcss,postcss,sss,vue}"
  lint:fix: pnpm lint:es:fix && pnpm lint:style:fix
  lint:es:fix: pnpm lint:es --fix
  lint:style:fix: pnpm lint:style --fix

  # Task to create package.json for tools that need it
  compile:packageJson: pnpx jiti scripts/compilePackageJson.ts

  # Workaround for:
  # - ESLint requiring a package.json
  # - Vitest to load ESM modules, as it needs to see "type": "module" in package.json
  # - Nuxt needing package.json to typecheck properly
  pnpm:devPreinstall: pnpm compile:packageJson

dependencies:
  # For linting
  ## This is in dependencies due to how Nuxt builds
  '@nuxt/eslint': ^1.9.0
  eslint: ^9.34.0
  eslint-plugin-unicorn: ^60.0.0
  eslint-plugin-vue-pug: ^0.6.2 # ESLint rules for Pug
  '@eslint/eslintrc': ^3.3.1 # To convert eslint-plugin-vue-pug to new ESLint flat config format
  yaml: ^2.8.1

  '@nuxt/fonts': ^0.11.4

  nuxt: ^4.0.3
  vue: ^3.5.19
  vue-router: ^4.5.1

devDependencies:
  # Enable use of TypeScript config files in various tools
  jiti: ^2.5.1

  # To use Sass
  sass-embedded: ^1.90.0

  # For testing
  '@nuxt/test-utils': ^3.19.2
  '@playwright/test': ^1.55.0
  '@vue/test-utils': ^2.4.6
  jsdom: ^26.1.0
  std-env: ^3.9.0
  vitest: ^3.2.4
  'monocart-reporter': ^2.9.21

  # For code quality checks on pre-commit
  husky: ^9.1.7
  lint-staged: ^16.1.5

  # To use Pug in Vue templates
  '@vue/language-plugin-pug': ^3.0.6 # Enables autocompletion for Vue components in Pug templates
  pug: ^3.0.3

  # To enable typechecking
  typescript: ^5.9.2
  vue-tsc: ^3.0.6
  '@types/node': ^24.3.0 # Allow typechecking of node code as well

  # For linting stylesheets
  '@nuxtjs/stylelint-module': ^5.2.1
  stylelint: ^16.23.1
  stylelint-config-standard-scss: ^15.0.1
  stylelint-config-standard-vue: ^1.0.0
  # Use SugarSS as a pseudo-sass parser due to postcss-sass not working with media queries
  postcss-sass: npm:sugarss@latest
  postcss-html: ^1.8.0
