name: nuxt-app
private: true
type: module

engines:
  node: ">= 22"
  pnpm: ">= 10.6.1"

scripts:
  build: nuxt build
  dev: nuxt dev
  generate: nuxt generate
  preview: nuxt preview
  postinstall: nuxt prepare
  typecheck: nuxt typecheck

  prepare: husky

  clean: pnpx jiti scripts/clean.ts

  test:unit:watch: vitest
  test:unit: vitest --run
  test:e2e:ui: playwright test --ui
  test:e2e: playwright test

  lint: pnpm lint:es && pnpm lint:style
  lint:es: eslint --max-warnings 0
  lint:style: stylelint  "**/*.{css,less,scss,sass,styl,stylus,pcss,postcss,sss,vue}"
  lint:fix: pnpm lint:es:fix && pnpm lint:style:fix
  lint:es:fix: pnpm lint:es --fix
  lint:style:fix: pnpm lint:style --fix

  # Task to create package.json for tools that need it
  compile:packageJson: pnpx jiti scripts/compilePackageJson.ts

  # Workaround for:
  # - ESLint requiring a package.json
  # - Vitest to load ESM modules, as it needs to see "type": "module" in package.json
  # - Nuxt needing package.json to typecheck properly
  pnpm:devPreinstall: pnpm compile:packageJson

dependencies:
  # For linting
  ## This is in dependencies due to how Nuxt builds
  "@nuxt/eslint": ^1.1.0
  eslint: ^9.22.0
  eslint-plugin-vue-pug: ^0.6.2 # ESLint rules for Pug
  "@eslint/eslintrc": ^3.3.0 # To convert eslint-plugin-vue-pug to new ESLint flat config format
  yaml: ^2.7.0

  "@nuxt/fonts": ^0.10.3

  nuxt: ^3.16.0
  vue: latest

devDependencies:
  # Enable use of TypeScript config files in various tools
  jiti: ^2.4.2

  # To use Sass
  sass-embedded: ^1.85.1

  # For testing
  "@nuxt/test-utils": ^3.17.1
  "@playwright/test": ^1.51.0
  "@vue/test-utils": ^2.4.6
  jsdom: ^26.0.0
  std-env: ^3.8.1
  vitest: ^3.0.8
  "monocart-reporter": ^2.9.15

  # For code quality checks on pre-commit
  husky: ^9.1.7
  lint-staged: ^15.4.3

  # To use Pug in Vue templates
  "@vue/language-plugin-pug": ^2.2.8 # Enables autocompletion for Vue components in Pug templates
  pug: ^3.0.3

  # To enable typechecking
  typescript: ^5.8.2
  vue-tsc: ^2.2.8

  # For linting stylesheets
  "@nuxtjs/stylelint-module": ^5.2.0
  stylelint: ^16.15.0
  stylelint-config-standard-scss: ^14.0.0
  stylelint-config-standard-vue: ^1.0.0
  # Use SugarSS as a pseudo-sass parser due to postcss-sass not working with media queries
  postcss-sass: npm:sugarss@latest
  postcss-html: ^1.8.0

packageManager: pnpm@10.6.1+sha512.40ee09af407fa9fbb5fbfb8e1cb40fbb74c0af0c3e10e9224d7b53c7658528615b2c92450e74cfad91e3a2dcafe3ce4050d80bda71d757756d2ce2b66213e9a3

pnpm:
  onlyBuiltDependencies:
    - "@parcel/watcher"
    - esbuild
