name: nuxt-template
private: true
type: module

devEngines:
  packageManager:
    name: pnpm
    version: 10.26.1+sha512.664074abc367d2c9324fdc18037097ce0a8f126034160f709928e9e9f95d98714347044e5c3164d65bd5da6c59c6be362b107546292a8eecb7999196e5ce58fa
    onFail: download

engines:
  node: '>= 24'

scripts:
  build: nuxt build
  dev: nuxt dev
  generate: nuxt generate
  preview: nuxt preview
  postinstall: nuxt prepare
  typecheck: nuxt typecheck

  prepare: husky

  clean: node scripts/clean.ts

  test:unit:watch: vitest
  test:unit: vitest --run
  test:e2e:ui: playwright test --ui
  test:e2e: playwright test

  lint: pnpm lint:es && pnpm lint:style
  lint:es: eslint --max-warnings 0
  lint:style: stylelint "**/*.{css,less,scss,sass,styl,stylus,pcss,postcss,sss,vue}"
  lint:fix: pnpm lint:es:fix && pnpm lint:style:fix
  lint:es:fix: pnpm lint:es --fix
  lint:style:fix: pnpm lint:style --fix

  # Task to create package.json for tools that need it
  compile:packageJson: node scripts/compile-package-json.ts

  # Workaround for:
  # - ESLint requiring a package.json
  # - Vitest to load ESM modules, as it needs to see "type": "module" in package.json
  # - Nuxt needing package.json to typecheck properly
  pnpm:devPreinstall: pnpm compile:packageJson

dependencies:
  '@nuxt/fonts': ^0.12.1
  '@nuxt/image': ^2.0.0

  vue-dompurify-html: ^5.3.0
  isomorphic-dompurify: ^2.34.0

  nuxt: ^4.2.2
  vue: ^3.5.25
  vue-router: ^4.6.4

devDependencies:
  # For linting
  '@nuxt/eslint': ^1.12.1
  eslint: ^9.39.2
  eslint-plugin-unicorn: ^62.0.0
  eslint-plugin-vue-pug: ^0.6.2 # ESLint rules for Pug
  '@vitest/eslint-plugin': ^1.5.2 # ESLint rules for Vitest
  eslint-plugin-playwright: ^2.4.0 # ESLint rules for Playwright
  eslint-plugin-testing-library: ^7.13.6 # ESLint rules for Testing Library
  '@eslint/eslintrc': ^3.3.3 # To convert eslint-plugin-vue-pug to new ESLint flat config format
  yaml: ^2.8.2

  # Enable use of TypeScript config files in various tools
  jiti: ^2.6.1

  # To use Sass
  sass-embedded: ^1.96.0

  # For testing
  '@nuxt/test-utils': ^3.21.0
  '@playwright/test': ^1.57.0
  '@vue/test-utils': ^2.4.6
  '@testing-library/vue': ^8.1.0
  jsdom: ^27.3.0
  std-env: ^3.10.0
  vitest: ^3.2.4
  'monocart-reporter': ^2.9.23

  # For code quality checks on pre-commit
  husky: ^9.1.7
  lint-staged: ^16.2.7

  # To enable typechecking
  typescript: ^5.9.3
  vue-tsc: &vue-tools ^3.1.8
  '@types/node': ^25.0.2 # Allow typechecking of node code as well

  # To use Pug in Vue templates
  '@vue/language-plugin-pug': *vue-tools # Enables autocompletion for Vue components in Pug templates
  pug: ^3.0.3

  # For linting stylesheets
  '@nuxtjs/stylelint-module': ^5.2.1
  stylelint: ^16.26.1
  stylelint-define-config: ^16.26.0
  '@stylelint-types/stylelint-scss': ^6.11.0
  '@stylelint-types/stylelint-stylistic': ^3.1.3
  stylelint-config-standard-scss: ^16.0.0
  stylelint-config-standard-vue: ^1.0.0
  '@stylistic/stylelint-config': ^3.0.1
  # Use SugarSS as a pseudo-sass parser due to postcss-sass not working with media queries
  postcss-sass: npm:sugarss@latest
  postcss-html: ^1.8.0
