name: nuxt-template
private: true
type: module

devEngines:
  packageManager:
    name: pnpm
    version: 10.18.0+sha512.e804f889f1cecc40d572db084eec3e4881739f8dec69c0ff10d2d1beff9a4e309383ba27b5b750059d7f4c149535b6cd0d2cb1ed3aeb739239a4284a68f40cfa
    onFail: download

engines:
  node: '>= 24'

scripts:
  build: nuxt build
  dev: nuxt dev
  generate: nuxt generate
  preview: nuxt preview
  postinstall: nuxt prepare
  typecheck: nuxt typecheck

  prepare: husky

  clean: node scripts/clean.ts

  test:unit:watch: vitest
  test:unit: vitest --run
  test:e2e:ui: playwright test --ui
  test:e2e: playwright test

  lint: pnpm lint:es && pnpm lint:style
  lint:es: eslint --max-warnings 0
  lint:style: stylelint "**/*.{css,less,scss,sass,styl,stylus,pcss,postcss,sss,vue}"
  lint:fix: pnpm lint:es:fix && pnpm lint:style:fix
  lint:es:fix: pnpm lint:es --fix
  lint:style:fix: pnpm lint:style --fix

  # Task to create package.json for tools that need it
  compile:packageJson: node scripts/compile-package-json.ts

  # Workaround for:
  # - ESLint requiring a package.json
  # - Vitest to load ESM modules, as it needs to see "type": "module" in package.json
  # - Nuxt needing package.json to typecheck properly
  pnpm:devPreinstall: pnpm compile:packageJson

dependencies:
  '@nuxt/fonts': ^0.11.4
  '@nuxt/image': ^1.11.0

  vue-dompurify-html: ^5.3.0
  isomorphic-dompurify: ^2.28.0

  nuxt: ^4.1.2
  vue: ^3.5.22
  vue-router: ^4.5.1

devDependencies:
  # For linting
  '@nuxt/eslint': ^1.9.0
  eslint: ^9.36.0
  eslint-plugin-unicorn: ^61.0.2
  eslint-plugin-vue-pug: ^0.6.2 # ESLint rules for Pug
  '@vitest/eslint-plugin': ^1.3.13 # ESLint rules for Vitest
  eslint-plugin-playwright: ^2.2.2 # ESLint rules for Playwright
  eslint-plugin-testing-library: ^7.11.0 # ESLint rules for Testing Library
  '@eslint/eslintrc': ^3.3.1 # To convert eslint-plugin-vue-pug to new ESLint flat config format
  yaml: ^2.8.1

  # Enable use of TypeScript config files in various tools
  jiti: ^2.6.0

  # To use Sass
  sass-embedded: ^1.93.2

  # For testing
  '@nuxt/test-utils': ^3.19.2
  '@playwright/test': ^1.55.1
  '@vue/test-utils': ^2.4.6
  '@testing-library/vue': ^8.1.0
  jsdom: ^27.0.0
  std-env: ^3.9.0
  vitest: ^3.2.4
  'monocart-reporter': ^2.9.23

  # For code quality checks on pre-commit
  husky: ^9.1.7
  lint-staged: ^16.2.1

  # To enable typechecking
  typescript: ^5.9.2
  vue-tsc: &vue-tools ^3.0.8
  '@types/node': ^24.5.2 # Allow typechecking of node code as well

  # To use Pug in Vue templates
  '@vue/language-plugin-pug': *vue-tools # Enables autocompletion for Vue components in Pug templates
  pug: ^3.0.3

  # For linting stylesheets
  '@nuxtjs/stylelint-module': ^5.2.1
  stylelint: ^16.24.0
  stylelint-define-config: ^16.24.0
  '@stylelint-types/stylelint-scss': ^6.11.0
  '@stylelint-types/stylelint-stylistic': ^3.1.3
  stylelint-config-standard-scss: ^16.0.0
  stylelint-config-standard-vue: ^1.0.0
  '@stylistic/stylelint-config': ^3.0.1
  # Use SugarSS as a pseudo-sass parser due to postcss-sass not working with media queries
  postcss-sass: npm:sugarss@latest
  postcss-html: ^1.8.0
