name: nuxt-template
private: true
type: module

devEngines:
  packageManager:
    name: pnpm
    version: 10.28.2+sha512.41872f037ad22f7348e3b1debbaf7e867cfd448f2726d9cf74c08f19507c31d2c8e7a11525b983febc2df640b5438dee6023ebb1f84ed43cc2d654d2bc326264
    onFail: download

engines:
  node: '>= 24'

scripts:
  build: nuxt build
  dev: nuxt dev
  generate: nuxt generate
  preview: nuxt preview
  postinstall: nuxt prepare
  typecheck: nuxt typecheck

  prepare: husky

  clean: node scripts/clean.ts

  test:unit:watch: vitest
  test:unit: vitest --run
  test:e2e:ui: playwright test --ui
  test:e2e: playwright test

  lint: pnpm lint:es && pnpm lint:style
  lint:es: eslint --max-warnings 0
  lint:style: stylelint "**/*.{css,less,scss,sass,styl,stylus,pcss,postcss,sss,vue}"
  lint:fix: pnpm lint:es:fix && pnpm lint:style:fix
  lint:es:fix: pnpm lint:es --fix
  lint:style:fix: pnpm lint:style --fix

  # Task to create package.json for tools that need it
  compile:packageJson: node scripts/compile-package-json.ts

  # Workaround for:
  # - ESLint requiring a package.json
  # - Vitest to load ESM modules, as it needs to see "type": "module" in package.json
  # - Nuxt needing package.json to typecheck properly
  pnpm:devPreinstall: pnpm compile:packageJson

dependencies:
  '@nuxt/fonts': ^0.13.0
  '@nuxt/image': ^2.0.0

  vue-dompurify-html: ^5.3.0
  isomorphic-dompurify: ^2.35.0

  nuxt: ^4.3.0
  vue: ^3.5.27
  vue-router: ^4.6.4

devDependencies:
  # For linting
  '@nuxt/eslint': ^1.13.0
  eslint: ^9.39.2
  eslint-plugin-unicorn: ^62.0.0
  eslint-plugin-vue-pug: ^0.6.2 # ESLint rules for Pug
  '@vitest/eslint-plugin': ^1.6.6 # ESLint rules for Vitest
  eslint-plugin-playwright: ^2.5.0 # ESLint rules for Playwright
  eslint-plugin-testing-library: ^7.15.4 # ESLint rules for Testing Library
  '@eslint/eslintrc': ^3.3.3 # To convert eslint-plugin-vue-pug to new ESLint flat config format
  yaml: ^2.8.2

  # Enable use of TypeScript config files in various tools
  jiti: ^2.6.1

  # To use Sass
  sass-embedded: ^1.97.3

  # For testing
  '@nuxt/test-utils': ^3.23.0
  '@playwright/test': ^1.58.0
  '@vue/test-utils': ^2.4.6
  '@testing-library/vue': ^8.1.0
  jsdom: ^27.4.0
  std-env: ^3.10.0
  vitest: ^3.2.4
  'monocart-reporter': ^2.9.23

  # For code quality checks on pre-commit
  husky: ^9.1.7
  lint-staged: ^16.2.7

  # To enable typechecking
  typescript: ^5.9.3
  vue-tsc: &vue-tools ^3.2.3
  '@types/node': ^24.10.6 # Allow typechecking of node code as well

  # To use Pug in Vue templates
  '@vue/language-plugin-pug': *vue-tools # Enables autocompletion for Vue components in Pug templates
  pug: ^3.0.3

  # For linting stylesheets
  '@nuxtjs/stylelint-module': ^5.2.1
  stylelint: ^17.0.0
  stylelint-define-config: ^17.0.0
  '@stylelint-types/stylelint-scss': ^7.0.0
  '@stylelint-types/stylelint-stylistic': ^5.0.0
  stylelint-config-standard-scss: ^17.0.0
  stylelint-config-standard-vue: ^1.0.0
  '@stylistic/stylelint-config': ^4.0.0
  # Use SugarSS as a pseudo-sass parser due to postcss-sass not working with media queries
  postcss-sass: npm:sugarss@latest
  postcss-html: ^1.8.1
