name: nuxt-app
private: true
type: module

engines:
  node: ">= 22"
  pnpm: ">= 9"

scripts:
  build: nuxt build
  dev: nuxt dev
  generate: nuxt generate
  preview: nuxt preview
  postinstall: nuxt prepare
  typecheck: nuxt typecheck

  prepare: husky

  test:unit:watch: vitest
  test:unit: vitest --run
  test:e2e:ui: playwright test --ui
  test:e2e: playwright test

  lint: pnpm lint:es && pnpm lint:style
  lint:es: eslint --flag unstable_ts_config --max-warnings 0
  lint:style: stylelint  "**/*.{css,less,scss,sass,pcss,postcss,sss,vue}"
  lint:fix: pnpm lint:es:fix && pnpm lint:style:fix
  lint:es:fix: pnpm lint:es --fix
  lint:style:fix: pnpm lint:style --fix

  # Task to create package.json for tools that need it
  create-package-json: pnpx jiti scripts/compile-package-json.ts

  # Workaround for:
  # - ESLint requiring a package.json
  # - Vitest to load ESM modules, as it needs to see "type": "module" in package.json
  # - Nuxt needing package.json to typecheck properly
  pnpm:devPreinstall: pnpm create-package-json

dependencies:
  # For linting
  "@nuxt/eslint": ^0.6.1
  eslint-plugin-vue-pug: ^0.6.2 # ESLint rules for Pug
  "@eslint/eslintrc": ^3.1.0 # To convert eslint-plugin-vue-pug to new ESLint flat config format
  "@types/eslint__eslintrc": ^2.1.2
  yaml: ^2.6.0

  "@nuxt/fonts": ^0.10.2

  nuxt: ^3.13.2
  vue: latest

devDependencies:
  # Enable use of TypeScript config files in various tools
  jiti: ^2.4.0

  # To use Sass
  sass-embedded: ^1.80.6

  # For testing
  "@nuxt/test-utils": ^3.14.4
  "@playwright/test": ^1.48.2
  "@vue/test-utils": ^2.4.6
  jsdom: ^25.0.1
  std-env: ^3.7.0
  vitest: ^2.1.4

  # For code quality checks on pre-commit
  husky: ^9.1.6
  "@types/lint-staged": ^13.3.0
  lint-staged: ^15.2.10

  # To use Pug in Vue templates
  "@vue/language-plugin-pug": ^2.1.10 # Enables autocompletion for Vue components in Pug templates
  pug: ^3.0.3

  # To enable typechecking
  typescript: ^5.6.3
  vue-tsc: ^2.1.10

  # For linting stylesheets
  "@nuxtjs/stylelint-module": ^5.2.0
  stylelint: ^16.10.0
  stylelint-config-standard-scss: ^13.1.0
  stylelint-config-standard-vue: ^1.0.0
  # Use SugarSS as a pseudo-sass parser due to postcss-sass not working with media queries
  postcss-sass: npm:sugarss@latest
  postcss-html: ^1.7.0

packageManager: pnpm@9.12.2+sha512.22721b3a11f81661ae1ec68ce1a7b879425a1ca5b991c975b074ac220b187ce56c708fe5db69f4c962c989452eee76c82877f4ee80f474cebd61ee13461b6228
