minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  # Trust packages that publish using trusted publishing
  - nuxt
  - '@nuxt/*'
  - eslint-plugin-testing-library
  - oxc-parser
  - '@oxc-parser/*'
  - oxc-minify
  - '@oxc-minify/*'
  - oxc-transform
  - '@oxc-transform/*'
  - '@oxc-project/types'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  # Remove any reference to @types/eslint due to conflict with ESLint's inbuilt type
  '@types/eslint': '-'
