onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  # Remove any reference to @types/eslint due to conflict with ESLint's inbuilt type
  '@types/eslint': '-'
