minimumReleaseAge: 10080

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  # Remove any reference to @types/eslint due to conflict with ESLint's inbuilt type
  '@types/eslint': '-'

  # Skip unstorage 1.17.2 due to broken types
  unstorage: <=1.17.1 || ^1.17.3
