packageExtensions:
  stylelint:
    dependencies:
      # Enable TypeScript config loading for Stylelint
      cosmiconfig-typescript-loader: ^6.1.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver

overrides:
  # Remove any reference to @types/eslint due to conflict with ESLint's inbuilt type
  '@types/eslint': '-'
