minimumReleaseAge: 10080

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  sharp: false
  unrs-resolver: false

patchedDependencies:
  '@stylelint-types/stylelint-scss': patches/@stylelint-types__stylelint-scss.patch
  eslint-plugin-vue-pug: patches/eslint-plugin-vue-pug.patch

overrides:
  # Remove any reference to @types/eslint due to conflict with ESLint's inbuilt type
  '@types/eslint': '-'

  # Skip unstorage 1.17.2 due to broken types
  unstorage: <=1.17.1 || ^1.17.3

  chokidar: ^5.0.0
